// payloadRaw (คอลัมน์จริงของ parcel CSV, หลัง trim) ของเจ้าของ 1 ราย — ใช้ทดสอบ buildWorklistItem
export const PARCEL_PAYLOAD: Record<string, string> = {
  "PARCEL_NO": "31635",
  "LAND_NO": "84",
  "UTM_MAP1": "5039",
  "UTM_MAP2": "2",
  "UTM_MAP3": "4682",
  "UTM_MAP4": "7",
  "UTM_SCALE": "1000",
  "SURVEY_NO": "13725",
  "OWN_TITLE": "นางสาว",
  "OWN_FNAME": "วรารีย์",
  "OWN_LNAME": "ชาลีรัตน์",
  "OWN_PERS_ID": "1 6097 00018 24 8",
  "OWN_HSE_NO": "29/5",
  "OWN_MOO": "",
  "OWN_SOI": "ทวีชัย 12",
  "OWN_VILLAGE": "",
  "OWN_ROAD": "",
  "OWN_TAMBOL": "ตาคลี",
  "OWN_AMPHUR": "ตาคลี",
  "OWN_PROVINCE": "นครสวรรค์",
};
